# coding: utf-8
#Converts .dat files generated by pyFAI into .xy files
#Can place this all in a loop to walk through other folders
#Written by Adam Corrao, 2018
import os
import pandas as pd
from shutil import copyfile
dat_dir = os.path.join('C:',os.sep,'Users','acorr','Khalifah_Group','Test_for_Dario')
os.chdir(dat_dir)
dat_files = [file for file in os.listdir() if file.endswith('.dat')]
for dat in dat_files:
    xy_file = dat.replace('.dat','.xy')
    data = pd.read_csv(dat,skiprows=23,header=None,delim_whitespace=True)
    data.columns = ['X','I']
    data.to_csv(xy_file,index=False,float_format='%.8f',sep='\t')